### ISSUE TITLE
new stable release 

### ISSUE THREAD

**Issue by eventhorizonpl** [chrisboulton/php-resque#238] opened 2015-03-18 09:26 UTC
Hi,

Is it possible to get new stable release in the near future?

Best regards,
Michal

**Comment by danhunsaker** [comment] 2015-03-18 19:56
Duplicate of #203 and #112.

**Comment by SrgSteak** [comment] 2015-11-06 11:59
👍🏻 Yeah, a new tag would be great. Still no stable release with dequeue mid 2015?

**Comment by chrisboulton** [comment] 2016-10-11 19:31
See #274

**Closed by chrisboulton** 2016-10-11 19:31 UTC
